;表示监听在 socket 上的 http server
[unix_http_server]
;设置 unix domain socket 文件路径，HTTP/XML-RPC 会监听在这里
file=/tmp/supervisor-taobei.sock

;关于 supervisord 进程的全局配置项
[supervisord]
;设置 log 文件路径
logfile=/tmp/supervisord-taobei.log
;设置 pid 文件路径
pidfile=/tmp/supervisord-taobei.pid

;这个是配置XML_RPC的，如果要使用supervisord或者web server这个选项必须要开启
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

;针对supervisorctl的配置
[supervisorctl]
;supervisorctl 本地连接 supervisord 时，本地 unix socket 路径，与前面的 [unix_http_server] 对应
serverurl=unix:///tmp/supervisor-taobei.sock

;具体监控的程序的配置项，书写格式为 [program:被监控程序名]
[program:tbbuy]
;启动程序使用的命令
command=python -u -m tbbuy.app
;配置进程的标准输出路径
stdout_logfile=/tmp/tbbuy.log
;配置进程的错误日志输出文件路径
stderr_logfile=/tmp/tbbuy.log

[program:tbfile]
command=python -u -m tbfile.app
stdout_logfile=/tmp/tbfile.log
stderr_logfile=/tmp/tbfile.log

[program:tbmall]
command=python -u -m tbmall.app
stdout_logfile=/tmp/tbmall.log
stderr_logfile=/tmp/tbmall.log

[program:tbuser]
command=python -u -m tbuser.app
stdout_logfile=/tmp/tbuser.log
stderr_logfile=/tmp/tbuser.log

[program:tbweb]
command=python -u -m tbweb.app
stdout_logfile=/tmp/tbweb.log
stderr_logfile=/tmp/tbweb.log
